version: "3.4"
services:
  pihole:
    image: pihole/pihole:2022.02.1
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    environment:
      # enter your docker host IP here
      ServerIP: ${ServerIP}
      # IPv6 Address if your network supports it
      ServerIPv6: ${ServerIPv6}
      DNS1: 127.0.0.1#5053
      DNS2: 127.0.0.1#5053
      DNSSEC: "true"
      DNSMASQ_LISTENING: "local"
      WEBPASSWORD: "${WEBPASSWORD}"
      SKIPGRAVITYONBOOT: "true"
    volumes:
      - './config-pihole:/etc/pihole/'
      - './config-dnsmasq:/etc/dnsmasq.d/'
    restart: always
    healthcheck:
      test: dig google.com @${ServerIP} +notcp && dig google.com @${ServerIPv6} +notcp
      interval: 15s
      timeout: 2s
      retries: 3
      start_period: 60s
    labels:
      autoheal: "true"
  cloudflared:
    image: crazymax/cloudflared@sha256:30659f561f8caf5b5d3f273aaf12e57774d0efe406405601c5e09f010e6cb398
    restart: always
    ports:
      - "5053:5053"
      - "5053:5053/udp"
    environment:
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_UPSTREAM: "https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    healthcheck:
      test: test $$(wget -qO - http://127.0.0.1:49312/healthcheck) = OK
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 15s
    labels:
      autoheal: "true"
  autoheal:
    image: pschmitt/autoheal@sha256:3b23c7f0be4bf939961ebd5eaec6f08b99775f5b0587df49093ac39241b9c25a
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

