services:
  pihole:
    image: pihole/pihole:2024.07.0
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    environment:
      DNS1: 127.0.0.1#5053
      DNS2: 127.0.0.1#5053
      DNSSEC: "true"
      DNSMASQ_LISTENING: "local"
      WEBPASSWORD: "${WEBPASSWORD}"
      SKIPGRAVITYONBOOT: "true"
    volumes:
      - './config-pihole:/etc/pihole/'
      - './config-dnsmasq:/etc/dnsmasq.d/'
    restart: always
    healthcheck:
      test: dig google.com @${ServerIP} +notcp && dig google.com @${ServerIPv6} +notcp
      interval: 15s
      timeout: 2s
      retries: 3
      start_period: 60s
    labels:
      autoheal: "true"
  cloudflared:
    image: crazymax/cloudflared@sha256:494a58d5a9d3aa45af33a84a5b2091270dc3bc734f9d5b9ac0cbf18f5b7a66a5
    restart: always
    ports:
      - "5053:5053"
      - "5053:5053/udp"
    environment:
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_UPSTREAM: "https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    healthcheck:
      test: test $$(wget -qO - http://127.0.0.1:49312/healthcheck) = OK
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 15s
    labels:
      autoheal: "true"
  autoheal:
    image: pschmitt/autoheal@sha256:a583ec8721bac6438e446c2b4357a5e347a9d5519efb0877652dbe268d9e5aa6
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  certbot:
    image: certbot/dns-cloudflare
    user: "1000:1000"
    volumes:
      - ./config-certbot:/certbot
    secrets:
      - source: cloudflare_api_token_ini
        target: cloudflare.ini
    restart: always
    entrypoint: /bin/sh
    command:
      - -c
      - |
        while true; do
          certbot renew \
            --logs-dir /certbot/logs \
            --work-dir /certbot/tmp \
            --config-dir /certbot/cfg \
            --non-interactive \
            --agree-tos \
            --dns-cloudflare \
            --dns-cloudflare-credentials /run/secrets/cloudflare.ini \
            --dns-cloudflare-propagation-seconds 30 \
            --email ${CLOUDFLARE_EMAIL};
          sleep 86400;
        done
  ghostunnel:
    image: ghostunnel/ghostunnel:v1.8.3
    network_mode: "host"
    volumes:
      - ./config-certbot:/certs
    environment:
      - DOMAIN
    command:
      - server
      - --listen=0.0.0.0:853
      - --target=localhost:53
      - --cert=/certs/cfg/live/${DOMAIN}/fullchain.pem
      - --key=/certs/cfg/live/${DOMAIN}/privkey.pem
      - --disable-authentication

secrets:
  cloudflare_api_token_ini:
    file: secrets/certbot-cloudflare.ini
